#[path = "../ex01_verificar_primeiro.rs"]
pub mod ex01_verificar_primeiro;
#[path = "../ex02_somar_lista.rs"]
pub mod ex02_somar_lista;
#[path = "../ex03_busca_binaria.rs"]
pub mod ex03_busca_binaria;
#[path = "../ex04_pares_com_soma.rs"]
pub mod ex04_pares_com_soma;
#[path = "../ex05_imprimir_pares_e_pares.rs"]
pub mod ex05_imprimir_pares_e_pares;
#[path = "../ex06_potencias_de_dois.rs"]
pub mod ex06_potencias_de_dois;
#[path = "../ex07_fibonacci_recursivo.rs"]
pub mod ex07_fibonacci_recursivo;
#[path = "../ex08_ordenacao_bolha.rs"]
pub mod ex08_ordenacao_bolha;
#[path = "../ex09_produto_de_matrizes.rs"]
pub mod ex09_produto_de_matrizes;
#[path = "../ex10_merge_sort.rs"]
pub mod ex10_merge_sort;
